[toolchain]
anchor_version = "0.31.1"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_distributor = "4fz5zanipjq9i2o9CwDXFZ9w6UyraqDo3uCv8AECD7Qe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "deploy-wallet.json"

[scripts]
test = "pnpm exec vitest run"

[hooks]
